apiVersion: v1
kind: Service
metadata:
  name: kapi-client
  labels:
    app: kapi-client
spec:
  selector:
    app: kapi-client
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
